# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KerberosSDR_GUI_Qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 1003)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget_config = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_config.setMaximumSize(QtCore.QSize(290, 16777215))
        self.stackedWidget_config.setObjectName("stackedWidget_config")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setObjectName("label_3")
        self.gridLayout_16.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_daq_ip_addr = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_daq_ip_addr.setObjectName("lineEdit_daq_ip_addr")
        self.gridLayout_16.addWidget(self.lineEdit_daq_ip_addr, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout_16.addWidget(self.label_10, 0, 0, 1, 1)
        self.doubleSpinBox_center_freq = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_center_freq.setDecimals(4)
        self.doubleSpinBox_center_freq.setMinimum(25.0)
        self.doubleSpinBox_center_freq.setMaximum(2000.0)
        self.doubleSpinBox_center_freq.setProperty("value", 100.0)
        self.doubleSpinBox_center_freq.setObjectName("doubleSpinBox_center_freq")
        self.gridLayout_16.addWidget(self.doubleSpinBox_center_freq, 1, 1, 1, 1)
        self.comboBox_gain = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_gain.setObjectName("comboBox_gain")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.comboBox_gain.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_gain, 2, 1, 1, 1)
        self.label_gain = QtWidgets.QLabel(self.groupBox_7)
        self.label_gain.setObjectName("label_gain")
        self.gridLayout_16.addWidget(self.label_gain, 2, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.pushButton_set_receiver_config = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_set_receiver_config.setObjectName("pushButton_set_receiver_config")
        self.gridLayout_17.addWidget(self.pushButton_set_receiver_config, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_7)
        self.checkBox_en_spectrum = QtWidgets.QCheckBox(self.page_4)
        self.checkBox_en_spectrum.setObjectName("checkBox_en_spectrum")
        self.verticalLayout_7.addWidget(self.checkBox_en_spectrum)
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_6.setMaximumSize(QtCore.QSize(290, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_37 = QtWidgets.QLabel(self.groupBox_6)
        self.label_37.setObjectName("label_37")
        self.gridLayout_14.addWidget(self.label_37, 2, 0, 1, 1)
        self.label_status_frame_index = QtWidgets.QLabel(self.groupBox_6)
        self.label_status_frame_index.setObjectName("label_status_frame_index")
        self.gridLayout_14.addWidget(self.label_status_frame_index, 3, 1, 1, 1)
        self.label_gain_list = QtWidgets.QLabel(self.groupBox_6)
        self.label_gain_list.setObjectName("label_gain_list")
        self.gridLayout_14.addWidget(self.label_gain_list, 13, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        self.label_35.setObjectName("label_35")
        self.gridLayout_14.addWidget(self.label_35, 12, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_6)
        self.label_36.setObjectName("label_36")
        self.gridLayout_14.addWidget(self.label_36, 3, 0, 1, 1)
        self.label_status_fs = QtWidgets.QLabel(self.groupBox_6)
        self.label_status_fs.setObjectName("label_status_fs")
        self.gridLayout_14.addWidget(self.label_status_fs, 11, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.gridLayout_14.addWidget(self.label_18, 5, 0, 1, 1)
        self.label_status_cpi = QtWidgets.QLabel(self.groupBox_6)
        self.label_status_cpi.setObjectName("label_status_cpi")
        self.gridLayout_14.addWidget(self.label_status_cpi, 12, 1, 1, 1)
        self.label_status_freq = QtWidgets.QLabel(self.groupBox_6)
        self.label_status_freq.setObjectName("label_status_freq")
        self.gridLayout_14.addWidget(self.label_status_freq, 9, 1, 1, 1)
        self.label_IQ_sync_state = QtWidgets.QLabel(self.groupBox_6)
        self.label_IQ_sync_state.setObjectName("label_IQ_sync_state")
        self.gridLayout_14.addWidget(self.label_IQ_sync_state, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setObjectName("label_12")
        self.gridLayout_14.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_status_frame_sync = QtWidgets.QLabel(self.groupBox_6)
        self.label_status_frame_sync.setObjectName("label_status_frame_sync")
        self.gridLayout_14.addWidget(self.label_status_frame_sync, 2, 1, 1, 1)
        self.label_sample_delay_sync_state = QtWidgets.QLabel(self.groupBox_6)
        self.label_sample_delay_sync_state.setObjectName("label_sample_delay_sync_state")
        self.gridLayout_14.addWidget(self.label_sample_delay_sync_state, 6, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setObjectName("label_13")
        self.gridLayout_14.addWidget(self.label_13, 7, 0, 1, 1)
        self.label_noise_source_state = QtWidgets.QLabel(self.groupBox_6)
        self.label_noise_source_state.setObjectName("label_noise_source_state")
        self.gridLayout_14.addWidget(self.label_noise_source_state, 8, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_6)
        self.label_29.setObjectName("label_29")
        self.gridLayout_14.addWidget(self.label_29, 13, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_14.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_14.addWidget(self.label_4, 9, 0, 1, 1)
        self.label_update_rate = QtWidgets.QLabel(self.groupBox_6)
        self.label_update_rate.setObjectName("label_update_rate")
        self.gridLayout_14.addWidget(self.label_update_rate, 1, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_6)
        self.label_33.setObjectName("label_33")
        self.gridLayout_14.addWidget(self.label_33, 11, 0, 1, 1)
        self.label_status_adc_fs = QtWidgets.QLabel(self.groupBox_6)
        self.label_status_adc_fs.setObjectName("label_status_adc_fs")
        self.gridLayout_14.addWidget(self.label_status_adc_fs, 10, 1, 1, 1)
        self.label_DAQ_subsys_state = QtWidgets.QLabel(self.groupBox_6)
        self.label_DAQ_subsys_state.setObjectName("label_DAQ_subsys_state")
        self.gridLayout_14.addWidget(self.label_DAQ_subsys_state, 5, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setObjectName("label_22")
        self.gridLayout_14.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setObjectName("label_14")
        self.gridLayout_14.addWidget(self.label_14, 8, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_6)
        self.label_34.setObjectName("label_34")
        self.gridLayout_14.addWidget(self.label_34, 10, 0, 1, 1)
        self.label_power_level = QtWidgets.QLabel(self.groupBox_6)
        self.label_power_level.setObjectName("label_power_level")
        self.gridLayout_14.addWidget(self.label_power_level, 4, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 1, 1, 1)
        self.pushButton_proc_control = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_proc_control.setObjectName("pushButton_proc_control")
        self.gridLayout_15.addWidget(self.pushButton_proc_control, 3, 1, 1, 1)
        self.pushButton_close = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_15.addWidget(self.pushButton_close, 4, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.stackedWidget_config.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_trigger_max_amplitude = QtWidgets.QLabel(self.groupBox)
        self.label_trigger_max_amplitude.setObjectName("label_trigger_max_amplitude")
        self.gridLayout_5.addWidget(self.label_trigger_max_amplitude, 2, 1, 1, 1)
        self.spinBox_trigger_channel = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_trigger_channel.setEnabled(True)
        self.spinBox_trigger_channel.setMinimum(0)
        self.spinBox_trigger_channel.setMaximum(0)
        self.spinBox_trigger_channel.setObjectName("spinBox_trigger_channel")
        self.gridLayout_5.addWidget(self.spinBox_trigger_channel, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 2, 0, 1, 1)
        self.doubleSpinBox_trigger_threshold = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_trigger_threshold.setDecimals(1)
        self.doubleSpinBox_trigger_threshold.setMinimum(-80.0)
        self.doubleSpinBox_trigger_threshold.setMaximum(0.0)
        self.doubleSpinBox_trigger_threshold.setSingleStep(1.0)
        self.doubleSpinBox_trigger_threshold.setProperty("value", 0.0)
        self.doubleSpinBox_trigger_threshold.setObjectName("doubleSpinBox_trigger_threshold")
        self.gridLayout_5.addWidget(self.doubleSpinBox_trigger_threshold, 3, 1, 1, 1)
        self.checkBox_en_squelch = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_en_squelch.setText("")
        self.checkBox_en_squelch.setObjectName("checkBox_en_squelch")
        self.gridLayout_5.addWidget(self.checkBox_en_squelch, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 4, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 3, 0, 1, 1)
        self.checkBox_en_squelch_display = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_en_squelch_display.setText("")
        self.checkBox_en_squelch_display.setObjectName("checkBox_en_squelch_display")
        self.gridLayout_5.addWidget(self.checkBox_en_squelch_display, 4, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.stackedWidget_config.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.doubleSpinBox_DOA_d = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_DOA_d.setDecimals(4)
        self.doubleSpinBox_DOA_d.setProperty("value", 0.5)
        self.doubleSpinBox_DOA_d.setObjectName("doubleSpinBox_DOA_d")
        self.gridLayout_4.addWidget(self.doubleSpinBox_DOA_d, 1, 1, 1, 1)
        self.comboBox_antenna_alignment = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_antenna_alignment.setObjectName("comboBox_antenna_alignment")
        self.comboBox_antenna_alignment.addItem("")
        self.comboBox_antenna_alignment.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_antenna_alignment, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 2, 0, 1, 1)
        self.label_DoA_ambiguity = QtWidgets.QLabel(self.groupBox_2)
        self.label_DoA_ambiguity.setObjectName("label_DoA_ambiguity")
        self.gridLayout_4.addWidget(self.label_DoA_ambiguity, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_en_DOA_Capon = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_Capon.setText("")
        self.checkBox_en_DOA_Capon.setObjectName("checkBox_en_DOA_Capon")
        self.gridLayout.addWidget(self.checkBox_en_DOA_Capon, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.checkBox_en_DOA_Bartlett = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_Bartlett.setText("")
        self.checkBox_en_DOA_Bartlett.setObjectName("checkBox_en_DOA_Bartlett")
        self.gridLayout.addWidget(self.checkBox_en_DOA_Bartlett, 2, 1, 1, 1)
        self.checkBox_en_DOA_MEM = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_MEM.setText("")
        self.checkBox_en_DOA_MEM.setObjectName("checkBox_en_DOA_MEM")
        self.gridLayout.addWidget(self.checkBox_en_DOA_MEM, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.checkBox_en_DOA_MUSIC = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_MUSIC.setText("")
        self.checkBox_en_DOA_MUSIC.setObjectName("checkBox_en_DOA_MUSIC")
        self.gridLayout.addWidget(self.checkBox_en_DOA_MUSIC, 5, 1, 1, 1)
        self.checkBox_en_DOA = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA.setText("")
        self.checkBox_en_DOA.setChecked(True)
        self.checkBox_en_DOA.setObjectName("checkBox_en_DOA")
        self.gridLayout.addWidget(self.checkBox_en_DOA, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 7, 0, 1, 1)
        self.checkBox_en_DOA_FB_avg = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_FB_avg.setText("")
        self.checkBox_en_DOA_FB_avg.setObjectName("checkBox_en_DOA_FB_avg")
        self.gridLayout.addWidget(self.checkBox_en_DOA_FB_avg, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.stackedWidget_config.addWidget(self.page_2)
        self.verticalLayout_6.addWidget(self.stackedWidget_config)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_spectrum = QtWidgets.QWidget()
        self.tab_spectrum.setObjectName("tab_spectrum")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_spectrum)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_spectrum = QtWidgets.QGridLayout()
        self.gridLayout_spectrum.setObjectName("gridLayout_spectrum")
        self.gridLayout_6.addLayout(self.gridLayout_spectrum, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_spectrum, "")
        self.tab_squelch = QtWidgets.QWidget()
        self.tab_squelch.setObjectName("tab_squelch")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_squelch)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_squelch = QtWidgets.QGridLayout()
        self.gridLayout_squelch.setObjectName("gridLayout_squelch")
        self.gridLayout_8.addLayout(self.gridLayout_squelch, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_squelch, "")
        self.tab_DOA = QtWidgets.QWidget()
        self.tab_DOA.setObjectName("tab_DOA")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_DOA)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_DOA = QtWidgets.QGridLayout()
        self.gridLayout_DOA.setObjectName("gridLayout_DOA")
        self.gridLayout_12.addLayout(self.gridLayout_DOA, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_DOA, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_config.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.checkBox_en_squelch.toggled['bool'].connect(self.spinBox_trigger_channel.setEnabled)
        self.checkBox_en_squelch.toggled['bool'].connect(self.doubleSpinBox_trigger_threshold.setEnabled)
        self.checkBox_en_squelch.toggled['bool'].connect(self.checkBox_en_squelch_display.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkBox_en_squelch, self.spinBox_trigger_channel)
        MainWindow.setTabOrder(self.spinBox_trigger_channel, self.doubleSpinBox_trigger_threshold)
        MainWindow.setTabOrder(self.doubleSpinBox_trigger_threshold, self.checkBox_en_squelch_display)
        MainWindow.setTabOrder(self.checkBox_en_squelch_display, self.comboBox_gain)
        MainWindow.setTabOrder(self.comboBox_gain, self.lineEdit_daq_ip_addr)
        MainWindow.setTabOrder(self.lineEdit_daq_ip_addr, self.pushButton_set_receiver_config)
        MainWindow.setTabOrder(self.pushButton_set_receiver_config, self.doubleSpinBox_center_freq)
        MainWindow.setTabOrder(self.doubleSpinBox_center_freq, self.comboBox_antenna_alignment)
        MainWindow.setTabOrder(self.comboBox_antenna_alignment, self.doubleSpinBox_DOA_d)
        MainWindow.setTabOrder(self.doubleSpinBox_DOA_d, self.checkBox_en_DOA_Capon)
        MainWindow.setTabOrder(self.checkBox_en_DOA_Capon, self.checkBox_en_DOA_Bartlett)
        MainWindow.setTabOrder(self.checkBox_en_DOA_Bartlett, self.checkBox_en_DOA_MEM)
        MainWindow.setTabOrder(self.checkBox_en_DOA_MEM, self.checkBox_en_DOA_MUSIC)
        MainWindow.setTabOrder(self.checkBox_en_DOA_MUSIC, self.checkBox_en_DOA)
        MainWindow.setTabOrder(self.checkBox_en_DOA, self.checkBox_en_DOA_FB_avg)
        MainWindow.setTabOrder(self.checkBox_en_DOA_FB_avg, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_7.setTitle(_translate("MainWindow", "DAQ Subsystem Configuration"))
        self.label_3.setText(_translate("MainWindow", "Center frequency [MHz]:"))
        self.lineEdit_daq_ip_addr.setText(_translate("MainWindow", "192.168.33.21"))
        self.label_10.setText(_translate("MainWindow", "IP address"))
        self.comboBox_gain.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_gain.setItemText(1, _translate("MainWindow", "0.9"))
        self.comboBox_gain.setItemText(2, _translate("MainWindow", "1.4"))
        self.comboBox_gain.setItemText(3, _translate("MainWindow", "2.7"))
        self.comboBox_gain.setItemText(4, _translate("MainWindow", "3.7"))
        self.comboBox_gain.setItemText(5, _translate("MainWindow", "7.7"))
        self.comboBox_gain.setItemText(6, _translate("MainWindow", "8.7"))
        self.comboBox_gain.setItemText(7, _translate("MainWindow", "12.5"))
        self.comboBox_gain.setItemText(8, _translate("MainWindow", "14.4"))
        self.comboBox_gain.setItemText(9, _translate("MainWindow", "15.7"))
        self.comboBox_gain.setItemText(10, _translate("MainWindow", "16.6"))
        self.comboBox_gain.setItemText(11, _translate("MainWindow", "19.7"))
        self.comboBox_gain.setItemText(12, _translate("MainWindow", "20.7"))
        self.comboBox_gain.setItemText(13, _translate("MainWindow", "22.9"))
        self.comboBox_gain.setItemText(14, _translate("MainWindow", "25.4"))
        self.comboBox_gain.setItemText(15, _translate("MainWindow", "28.0"))
        self.comboBox_gain.setItemText(16, _translate("MainWindow", "29.7"))
        self.comboBox_gain.setItemText(17, _translate("MainWindow", "32.8"))
        self.comboBox_gain.setItemText(18, _translate("MainWindow", "33.8"))
        self.comboBox_gain.setItemText(19, _translate("MainWindow", "36.4"))
        self.comboBox_gain.setItemText(20, _translate("MainWindow", "37.2"))
        self.comboBox_gain.setItemText(21, _translate("MainWindow", "38.6"))
        self.comboBox_gain.setItemText(22, _translate("MainWindow", "40.2"))
        self.comboBox_gain.setItemText(23, _translate("MainWindow", "42.1"))
        self.comboBox_gain.setItemText(24, _translate("MainWindow", "43.4"))
        self.comboBox_gain.setItemText(25, _translate("MainWindow", "43.9"))
        self.comboBox_gain.setItemText(26, _translate("MainWindow", "44.5"))
        self.comboBox_gain.setItemText(27, _translate("MainWindow", "48.0"))
        self.comboBox_gain.setItemText(28, _translate("MainWindow", "49.6"))
        self.label_gain.setToolTip(_translate("MainWindow", "<html><head/><body><p>This gain value is unified for all the receiver channels</p></body></html>"))
        self.label_gain.setText(_translate("MainWindow", "IF gain  [dB]:"))
        self.pushButton_set_receiver_config.setText(_translate("MainWindow", "Set"))
        self.checkBox_en_spectrum.setText(_translate("MainWindow", "Enable spectrum display"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Status "))
        self.label_37.setText(_translate("MainWindow", "Frame sync:"))
        self.label_status_frame_index.setText(_translate("MainWindow", "-"))
        self.label_gain_list.setText(_translate("MainWindow", "-"))
        self.label_35.setText(_translate("MainWindow", "Data block size"))
        self.label_36.setText(_translate("MainWindow", "Frame index:"))
        self.label_status_fs.setText(_translate("MainWindow", "- MHz"))
        self.label_18.setText(_translate("MainWindow", "DAQ Subsystem state:"))
        self.label_status_cpi.setText(_translate("MainWindow", "- ms"))
        self.label_status_freq.setText(_translate("MainWindow", "- MHz"))
        self.label_IQ_sync_state.setText(_translate("MainWindow", "Unknown"))
        self.label_12.setText(_translate("MainWindow", "Sample delay sync:"))
        self.label_status_frame_sync.setText(_translate("MainWindow", "-"))
        self.label_sample_delay_sync_state.setText(_translate("MainWindow", "Unknown"))
        self.label_13.setText(_translate("MainWindow", "IQ sync:"))
        self.label_noise_source_state.setText(_translate("MainWindow", "Unknown"))
        self.label_29.setText(_translate("MainWindow", "IF gains [dB]:"))
        self.label_17.setText(_translate("MainWindow", "Powel level:"))
        self.label_4.setText(_translate("MainWindow", "Center frequency:"))
        self.label_update_rate.setText(_translate("MainWindow", "-ms"))
        self.label_33.setText(_translate("MainWindow", "Sampling frequency:"))
        self.label_status_adc_fs.setText(_translate("MainWindow", "- MHz"))
        self.label_DAQ_subsys_state.setText(_translate("MainWindow", "Not Connected"))
        self.label_22.setText(_translate("MainWindow", "Update rate:"))
        self.label_14.setText(_translate("MainWindow", "Noise source state:"))
        self.label_34.setText(_translate("MainWindow", "ADC sampling frequency:"))
        self.label_power_level.setText(_translate("MainWindow", "OK"))
        self.pushButton_proc_control.setText(_translate("MainWindow", "Start processing"))
        self.pushButton_close.setText(_translate("MainWindow", "Exit"))
        self.groupBox.setTitle(_translate("MainWindow", "Squelch configuration"))
        self.label_trigger_max_amplitude.setText(_translate("MainWindow", "-"))
        self.spinBox_trigger_channel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Can not be controlled in the current version!</p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "Trigger channel:"))
        self.label_23.setText(_translate("MainWindow", "Max amplitude [dBFS]: "))
        self.doubleSpinBox_trigger_threshold.setToolTip(_translate("MainWindow", "<html><head/><body><p>0 dBFS is equal to the maximum output level of the ADC</p><p>Set -80 dBFS to disable the trigger condition.</p></body></html>"))
        self.checkBox_en_squelch.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enables/Disables the squelch feature in the DoA DSP GUI. <br/>(Does not control the DAQ Subsystem)</p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "Enable  squelch"))
        self.label_28.setText(_translate("MainWindow", "Enable squelch display"))
        self.label_26.setText(_translate("MainWindow", "Trigger threshold [dBFS]:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Antenna configarion"))
        self.comboBox_antenna_alignment.setToolTip(_translate("MainWindow", "<html><head/><body><p>ULA (Uniform Linear Array)<br/>UCA (Uniform Ciruclar Array)</p></body></html>"))
        self.comboBox_antenna_alignment.setItemText(0, _translate("MainWindow", "ULA"))
        self.comboBox_antenna_alignment.setItemText(1, _translate("MainWindow", "UCA"))
        self.label_24.setText(_translate("MainWindow", "Spacing [meters]:"))
        self.label_21.setText(_translate("MainWindow", "Arrangement:"))
        self.label_38.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#a40000;\">Maximum phase difference between antenna elements should less than 180 deg to avoid ambiguities!</span></p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "Max phase diff:"))
        self.label_DoA_ambiguity.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#a40000;\">Maximum phase difference between antenna elements should less than 180 deg to avoid ambiguities!</span></p></body></html>"))
        self.label_DoA_ambiguity.setText(_translate("MainWindow", "-"))
        self.groupBox_4.setTitle(_translate("MainWindow", "DOA estimation"))
        self.label_9.setText(_translate("MainWindow", "MUSIC"))
        self.label_11.setText(_translate("MainWindow", "Enable/Disable:"))
        self.label_8.setText(_translate("MainWindow", "MEM"))
        self.label_7.setText(_translate("MainWindow", "Capon"))
        self.label_6.setText(_translate("MainWindow", "Bartlett"))
        self.label_16.setText(_translate("MainWindow", "FB average:"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; font-style:italic;\">Methods:</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; font-style:italic;\">Spatial decorrelation</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_spectrum), _translate("MainWindow", "Configuration and Spectrum"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_squelch), _translate("MainWindow", "Squelch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DOA), _translate("MainWindow", "DOA estimation"))
