name: flake8 Linting

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - uses: py-actions/flake8@v2
        with:
          plugins: "flake8-bugbear flake8-black Flake8-pyproject"